apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstorepetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstorepetservice
  template:
    metadata:
      labels:
        app: aks-petstorepetservice
    spec:
      nodeSelector:
        agentpool: petstorenp2
      containers:
      - name: aks-petstorepetservice
        image: paulazurepetstorecr.azurecr.io/petstorepetservice:latest
        ports:
        - containerPort: 80
        env:
        - name: PETSTOREPETSERVICE_SERVER_PORT
          value: "80"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: application-insights
              key: connection-string

        - name: APPLICATIONINSIGHTS_ROLE_NAME
          value: "petstore-pet-service"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-petstorepetservice 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-petstorepetservice
